### ISSUE TITLE
Update pipes-rs repo URL

### ISSUE THREAD

**Issue by lhvy** [KnotUntied/scoop-knotuntied#1]
Hi there! I just changed my GitHub username. In case someone makes an account with my old username and redirects stop working, I'd recommend changing the URL of pipes-rs in [pipes-rs.json](https://github.com/KnotUntied/scoop-knotuntied/blob/master/bucket/pipes-rs.json).

**Comment by KnotUntied** [comment]
Noted. Will push changes accordingly.

**Comment by KnotUntied** [comment]
Done. See beeae13b465fb22fae4c11b1b58839b958ff218e
